# (PART) Programação {-}

# Introdução à programação

Arquitetura abstrata, linguagem de máquina, assembly, linguagens de alto nível, meu primeiro programa.

## Linguagem de alto nível

Toda linguagem de programação possui uma sintaxe que define a estrutura em que
deve ser escrita.  Nas linguagens de programação de alto nível, além da
sintaxe, a semântica dos elementos também deve ser respeitada.  Por exemplo, ao
contrário das linguagens de montagem, devemos seguir regras semânticas quanto
ao tipo de cada variável do código.

De maneira geral, podemos dividir um programa em níveis de complexidade, ou seja,
aplicarmos o conceito de *abstração*:

- Um programa é composto por *subprogramas*;
- Subprogramas são compostos por conjuntos de *definições* e sequências de
  *comandos*;
- Cada definição ou comando é uma sequência de *tokens*; e
- Cada token é a unidade léxica mínima do programa.

## Primeiro programa de alto nível

Como vimos anteriormente, linguagens de programação de alto nível permitem ao
programador construir um software composto por diversos módulos. Neste caso, é
necessário identificar o "ponto de entrada" do programa. Ou seja, dentre as
diversas potenciais funcionalidades do programa, qual é a primeira instrução
executada.

Em C++17, o início do programa ocorre na função `main`. Esta é a função que o
sistema operacional invoca quando o programa é executado — outras rotinas podem
ser executadas antes da `main`, por exemplo, para inicializar variáveis
globais; no entanto, estes detalhes estão fora do escopo deste livro. Veja mais
informações [aqui](https://en.cppreference.com/w/cpp/language/main_function).

```{cpp}
// hello.cpp
#include <iostream>
auto main() -> int {
  std::cout << "Hello, world!\n";
}
```

Há várias nuances deste programa que entraremos em detalhes futuramente. No
momento, é suficiente saber que esse arquivo, quando compilado e executado,
resultará em uma saída com o texto `"Hello, world!"` seguido de quebra de linha.

```
$ g++ -std=c++17 hello.cpp -o hello
$ ./hello
Hello, world!
```
