---
title: "Computando"
subtitle: "Uma abordagem prática a programação, algoritmos e estruturas de dados"
author:
  - Filipe A. N. Verri
  - Lourenço A. Pereira Jr.
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
biblio-title: Referências
link-citations: yes
github-repo: verri/computing-book
description: ""
---

# Prefácio {-}

Já se perguntou o que, de fato, é Computação? Como ela está relacionada com a
Informática? E com os computadores digitais? Estes conceitos são fortemente
ligados, mas, de maneira alguma, são as mesmas coisas.

Neste livro, pretendo, de uma maneira prática, expor estes conceitos e
prepará-lo para o universo da programação independente da sua área de atuação.
Espero que futuros engenheiros, cientistas da computação, cientistas de dados,
biólogos, químicos, matemáticos e outros graduandos se beneficiem desse
material.

Veja que este não é um curso de programação numa linguagem específica, nem
mesmo um curso de introdução às Ciências de Computação (o que julgo muito mais
abrangente do que o escopo deste livro).

No entanto, meu intuito é habilitá-los a resolver problemas computacionais de
maneira organizada e efetiva, independentemente da linguagem de programação ou
área de domínio.  Inclusive, este não é um livro que tem como objetivo ensinar
todos os aspectos de determinada linguagem de programação.  Na medida do
possível, os leitores serão direcionados a materiais específicos a esta ou
aquela linguagem de programação.

Apresentarei os principais algoritmos e estruturas de dados utilizados na
atualidade -- consequentemente sou forçado a deixar de fora tópicos históricos
ou muito avançados.  É altamente recomendado que o leitor tenha familiaridade
com símbolos e notações matemáticas.

A sequência dos tópicos e a profundidade de cada um deles é fortemente baseada
na minha experiência nas disciplinas básicas de programação do Instituto
Tecnológico de Aeronáutica, e devem funcionar muito bem para qualquer outro
curso de engenharia.  No entanto, peço encarecidamente que não utilizem esse
material desatualizado -- nada pior para os alunos do que aprender arcaísmos.
Esta é uma área que está em constante evolução e assuntos desatualizados podem
prejudicar significantemente os alunos que formamos.

--- Filipe Verri

# Sobre os autores {-}

- [Filipe Verri](http://www.comp.ita.br/~verri/)
- [Lourenço Pereira Jr.](http://www.comp.ita.br/~ljr/)

# Agradecimentos {-}

Agradeço ao [Prof. Johnny Marques](http://www.comp.ita.br/~johnny/) por disponibilizar seu
material didático para o preparo do Capítulo sobre Complexidade Computacional e vários
capítulos da Parte III Estruturas de Dados.

# Guia ITA {-}

Este livro é utilizado como bibliografia complementar nas disciplinas CES-10 e CES-11 do
ITA.

Para facilitar o acompanhamento destas disciplinas, disponibilizamos um guia conectando os
tópicos da ementa com os capítulos deste livro.

Table: CES-10 -- Introdução à Computação

-----------------------------------------------------------------------------------------
Ementa                                         Capítulos
---------------------------------------------  ------------------------------------------
Conceitos primários: computador, algoritmo,    Capítulo \@ref(preliminares), \@ref(numeros),
programa, linguagem de programação,            \@ref(logica) e \@ref(representacao)
compilador.

Software básico para computadores.             Capítulo \@ref(programas) e \@ref(algoritmos)

Comandos de uma linguagem procedimental:       Capítulos \@ref(fluxo) e \@ref(io)
atribuição, entrada e saída, condicionais,
repetitivos e seletivos. Tratamento de
excecções.

Tipos escalares e estruturados.                Capítulos \@ref(programas) e \@ref(tipos)

Subprogramação: funções,                       Capítulo \@ref(subprogramas)
passagem de parâmetros por valor e
por referência, escopo de variáveis,
e recursividade.

Ponteiros.                                     Capítulo \@ref(memoria)
-----------------------------------------------------------------------------------------


Table: CES-11 -- Algoritmos e Estruturas de Dados I

-----------------------------------------------------------------------------------------
Ementa                                         Capítulos
---------------------------------------------  ------------------------------------------
Tópicos em recursividade.

Noções de complexidade de algoritmos.

Vetores e encadeamento de estruturas.

Pilhas, filas e deques.

Árvores gerais e binárias.

Grafos orientados e não orientados.

Algoritmos básicos para grafos.

Filas de prioridade.

Métodos básicos de ordenação.

Noções de programação orientada a objetos.
-----------------------------------------------------------------------------------------

<!-- vim: set spell spelllang=pt tw=90: -->
